### PR TITLE
Closes https://github.com/Fabriquartz/ember-right-click-menu/issues/30

### PR DESCRIPTION
**Pull request by Alexander-Krause-Glau**
- Updates Dependencies
- Fixes https://github.com/Fabriquartz/ember-right-click-menu/issues/30
- Works for Embroider and Classic

### CODE REVIEW

**Comment by Haz901** [comment]
Hi! Thanks for the fix, but it seems like we're having some issues with Travis... I'll try to migrate this addon to GitHub actions ASAP so we can get this update moving

**Comment by Haz901** [comment]
@Alexander-Krause-Glau The migration to GitHub Actions has been done in #32, If you could rebase or update this branch, we should be good to go

**Comment by Alexander-Krause-Glau** [comment]
> @Alexander-Krause-Glau The migration to GitHub Actions has been done in #32, If you could rebase or update this branch, we should be good to go

Done. Let's see if the workflow approves the PR.

**Comment by michaelw8** [comment]
I'm sorry it took so long, but a new version has been released (0.8.0) with the change you suggested and the packages updated. A few months ago I tried to complete your pull request, but couldn't get the addon to work, but now I've succeeded. Thank you for your contribution!

**Pull request closed without merging**
